### ISSUE TITLE
Great Example - but very unsecure

### ISSUE THREAD

**Issue by davidmann4** [jmg/node-simple-chat#1]
To avoid XSS better replace special chars with HTML entities - but for a example its good enough!

steps to reproduce: send message <script>alert("XSS");</script> 

thx for this great tutorial project - helps me learning this stuff!

**Comment by jmg** [comment]
Hey @davidmann4,

First at all, Thanks! You made a good point. It's very insecure, but just a demo project, it's not intended to be a production software.
Anyway, I found a nice implementation of the html_entities function of php in javascript. You can use it to make it avoid XSS ;)

http://phpjs.org/functions/htmlentities/
